Vagrant.configure("2") do |config|
  vm_name = ENV['VM_NAME'] || "ubuntu22.04.2"
  box_name = ENV['VAGRANT_BOX_NAME'] || "ubuntu22.04.2.box"

  config.vm.provider "hyperv" do |v|
    v.vmname = vm_name
    v.memory = 4096
    v.cpus = 2

    config.ssh.username = "vagrant"
    # config.ssh.password = "vagrant"

    # If you need a copy, find it here https://github.com/hashicorp/vagrant/blob/main/keys/vagrant.key.rsa
    config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  end

  config.vm.box = box_name
  config.vm.hostname = vm_name
  config.vm.network "public_network", bridge: "Default Switch"
  config.vm.boot_timeout = 1000
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "scripts/prep-xrdp.sh", privileged: true
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
    echo 'Rebooting now...'
    nohup bash -c 'sleep 5 && sudo reboot' &
    exit
  SHELL

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    echo 'System rebooted'
    # Continue with the rest of your script here
  SHELL
end
